import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CopyIcon, FlaskConicalIcon, SaveIcon, SendIcon } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'

import { apiGet, apiPost, apiPut } from '@/api/client'
import type { CronSettings, DataResponse, LoginSettings, NotificationSettings, OperationResult, ProxySettings } from '@/api/types'
import { useSession } from '@/auth/session-context'
import { LoadingTable } from '@/components/loading-table'
import { PageHeader } from '@/components/page-header'
import { QueryError } from '@/components/query-error'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Spinner } from '@/components/ui/spinner'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { toast } from '@/components/ui/toast'
import { useApiMutation } from '@/hooks/use-api-mutation'
import { displayValue } from '@/lib/format'
import { CertificateSettingsPanel } from '@/pages/certificate-settings-page'

export function SystemPage() {
  const session = useSession()
  const [searchParams, setSearchParams] = useSearchParams()
  const requestedTab = searchParams.get('tab')
  const allowedTabs = session.capabilities.certificates ? ['notifications', 'proxy', 'cron', 'login', 'certificates'] : ['notifications', 'proxy', 'cron', 'login']
  const tab = allowedTabs.includes(requestedTab ?? '') ? requestedTab! : 'notifications'
  return <div className="flex flex-col gap-6"><PageHeader eyebrow="管理" title="系统设置" description="配置通知通道、网络代理、后台任务、登录验证与证书自动化。" /><Tabs value={tab} onValueChange={(value) => setSearchParams(value === 'notifications' ? {} : { tab: value }, { replace: true })}><TabsList variant="line"><TabsTrigger value="notifications">通知</TabsTrigger><TabsTrigger value="proxy">网络代理</TabsTrigger><TabsTrigger value="cron">后台任务</TabsTrigger><TabsTrigger value="login">登录设置</TabsTrigger>{session.capabilities.certificates ? <TabsTrigger value="certificates">证书设置</TabsTrigger> : null}</TabsList><TabsContent value="notifications"><NotificationSettingsPanel /></TabsContent><TabsContent value="proxy"><ProxySettingsPanel /></TabsContent><TabsContent value="cron"><CronSettingsPanel /></TabsContent><TabsContent value="login"><LoginSettingsPanel /></TabsContent>{session.capabilities.certificates ? <TabsContent value="certificates"><CertificateSettingsPanel /></TabsContent> : null}</Tabs></div>
}

function LoginSettingsPanel() {
  const query = useQuery({ queryKey: ['system-login-settings'], queryFn: async () => (await apiGet<DataResponse<LoginSettings>>('/api/web/v1/system/login-settings')).data })
  const save = useApiMutation<boolean, DataResponse<OperationResult>>({ mutationFn: (enabled) => apiPut('/api/web/v1/system/login-settings', { graphicalVerificationEnabled: enabled }), successMessage: '登录设置已保存', invalidate: [['system-login-settings']] })
  if (query.isError) return <QueryError error={query.error} retry={() => void query.refetch()} />
  if (query.isPending) return <LoadingTable />
  return <Card><CardHeader><CardTitle>图形验证码</CardTitle><CardDescription>控制本地登录入口是否要求图形验证码。</CardDescription></CardHeader><CardContent><Field orientation="horizontal"><div className="flex-1"><FieldLabel htmlFor="login-captcha">启用图形验证码</FieldLabel><FieldDescription>{query.data.appliesToCurrentLogin ? '设置会应用到当前登录入口。' : '设置会保留给支持本地凭据的登录入口。'}</FieldDescription></div><Switch id="login-captcha" checked={query.data.graphicalVerificationEnabled} disabled={save.isPending} onCheckedChange={(checked) => save.mutate(checked)} /></Field></CardContent></Card>
}

function NotificationSettingsPanel() {
  const query = useQuery({ queryKey: ['system-notifications'], queryFn: async () => (await apiGet<DataResponse<NotificationSettings>>('/api/web/v1/system/notifications')).data })
  const [values, setValues] = useState<NotificationSettings | null>(null)
  useEffect(() => { if (query.data) setValues(query.data) }, [query.data])
  const save = useApiMutation<Partial<NotificationSettings>, DataResponse<OperationResult>>({ mutationFn: (body) => apiPut('/api/web/v1/system/notifications', body), successMessage: '通知设置已保存', invalidate: [['system-notifications']] })
  const test = useApiMutation<string, DataResponse<OperationResult>>({ mutationFn: (channel) => apiPost('/api/web/v1/system/notifications/test', { channel }), successMessage: '测试通知已发送' })
  if (query.isError) return <QueryError error={query.error} retry={() => void query.refetch()} />
  if (!values) return <LoadingTable />
  return <div className="grid gap-4 lg:grid-cols-2">
    <SettingsCard title="邮件" description="SMTP、SendCloud 或阿里云邮件服务。" onSave={() => save.mutate({ email: values.email })} onTest={() => test.mutate('email')} pending={save.isPending || test.isPending}><FieldGroup><Field><FieldLabel>服务类型</FieldLabel><Select items={[{ value: 'smtp', label: 'SMTP' }, { value: 'sendcloud', label: 'SendCloud' }, { value: 'aliyun', label: '阿里云' }]} value={values.email.provider} onValueChange={(provider) => setValues({ ...values, email: { ...values.email, provider: provider as NotificationSettings['email']['provider'] } })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="smtp">SMTP</SelectItem><SelectItem value="sendcloud">SendCloud</SelectItem><SelectItem value="aliyun">阿里云</SelectItem></SelectGroup></SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><TextField label="服务器" value={values.email.smtpServer} onChange={(smtpServer) => setValues({ ...values, email: { ...values.email, smtpServer } })} /><NumberField label="端口" value={values.email.smtpPort} onChange={(smtpPort) => setValues({ ...values, email: { ...values.email, smtpPort } })} /></div><TextField label="发件人" value={values.email.sender} onChange={(sender) => setValues({ ...values, email: { ...values.email, sender } })} /><TextField label="密码 / Secret" type="password" value={values.email.password} onChange={(password) => setValues({ ...values, email: { ...values.email, password } })} /><TextField label="API User" value={values.email.apiUser} onChange={(apiUser) => setValues({ ...values, email: { ...values.email, apiUser } })} /><TextField label="API Key" type="password" value={values.email.apiKey} onChange={(apiKey) => setValues({ ...values, email: { ...values.email, apiKey } })} /><TextField label="收件人" value={values.email.recipient} onChange={(recipient) => setValues({ ...values, email: { ...values.email, recipient } })} /></FieldGroup></SettingsCard>
    <SettingsCard title="Telegram" description="通过 Telegram Bot 发送通知。" onSave={() => save.mutate({ telegram: values.telegram })} onTest={() => test.mutate('telegram')} pending={save.isPending || test.isPending}><FieldGroup><TextField label="Bot Token" type="password" value={values.telegram.token} onChange={(token) => setValues({ ...values, telegram: { ...values.telegram, token } })} /><div className="grid gap-4 sm:grid-cols-2"><TextField label="Chat ID" value={values.telegram.chatId} onChange={(chatId) => setValues({ ...values, telegram: { ...values.telegram, chatId } })} /><TextField label="Topic ID" value={values.telegram.topicId} onChange={(topicId) => setValues({ ...values, telegram: { ...values.telegram, topicId } })} /></div><Field><FieldLabel>代理模式</FieldLabel><Select items={[{ value: 'off', label: '不使用代理' }, { value: 'system', label: '系统代理' }, { value: 'custom', label: '自定义 API 地址' }]} value={values.telegram.proxyMode} onValueChange={(proxyMode) => setValues({ ...values, telegram: { ...values.telegram, proxyMode: proxyMode as NotificationSettings['telegram']['proxyMode'] } })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="off">不使用代理</SelectItem><SelectItem value="system">系统代理</SelectItem><SelectItem value="custom">自定义 API 地址</SelectItem></SelectGroup></SelectContent></Select></Field>{values.telegram.proxyMode === 'custom' ? <TextField label="自定义 API 地址" value={values.telegram.customBaseUrl} onChange={(customBaseUrl) => setValues({ ...values, telegram: { ...values.telegram, customBaseUrl } })} /> : null}</FieldGroup></SettingsCard>
    <SettingsCard title="群机器人 Webhook" description="适用于企业微信、飞书或兼容 Webhook。" onSave={() => save.mutate({ robotWebhook: values.robotWebhook })} onTest={() => test.mutate('robot-webhook')} pending={save.isPending || test.isPending}><FieldGroup><TextField label="Webhook URL" value={values.robotWebhook.url} onChange={(url) => setValues({ ...values, robotWebhook: { ...values.robotWebhook, url } })} /><TextField label="提醒对象" value={values.robotWebhook.mention} onChange={(mention) => setValues({ ...values, robotWebhook: { ...values.robotWebhook, mention } })} /></FieldGroup></SettingsCard>
    <SettingsCard title="自定义 Webhook" description="使用自定义请求方法、头部与正文模板。" onSave={() => save.mutate({ customWebhook: values.customWebhook })} onTest={() => test.mutate('custom-webhook')} pending={save.isPending || test.isPending}><FieldGroup><TextField label="Webhook URL" value={values.customWebhook.url} onChange={(url) => setValues({ ...values, customWebhook: { ...values.customWebhook, url } })} /><div className="grid gap-4 sm:grid-cols-2"><SelectField label="请求方法" value={values.customWebhook.method} options={['GET', 'POST', 'PUT']} onChange={(method) => setValues({ ...values, customWebhook: { ...values.customWebhook, method: method as 'GET' | 'POST' | 'PUT' } })} /><SelectField label="内容格式" value={values.customWebhook.contentFormat} options={['html', 'markdown', 'text']} onChange={(contentFormat) => setValues({ ...values, customWebhook: { ...values.customWebhook, contentFormat: contentFormat as 'html' | 'markdown' | 'text' } })} /></div><SelectField label="Content-Type" value={values.customWebhook.contentType} options={['application/json', 'application/x-www-form-urlencoded']} onChange={(contentType) => setValues({ ...values, customWebhook: { ...values.customWebhook, contentType: contentType as NotificationSettings['customWebhook']['contentType'] } })} /><AreaField label="请求头" value={values.customWebhook.headers} onChange={(headers) => setValues({ ...values, customWebhook: { ...values.customWebhook, headers } })} /><AreaField label="请求正文" value={values.customWebhook.body} onChange={(body) => setValues({ ...values, customWebhook: { ...values.customWebhook, body } })} /></FieldGroup></SettingsCard>
    <SettingsCard title="微信模板消息" description="配置应用 Token 与接收用户。" onSave={() => save.mutate({ wechat: values.wechat })} pending={save.isPending}><FieldGroup><TextField label="App Token" type="password" value={values.wechat.appToken} onChange={(appToken) => setValues({ ...values, wechat: { ...values.wechat, appToken } })} /><TextField label="用户 ID" value={values.wechat.userId} onChange={(userId) => setValues({ ...values, wechat: { ...values.wechat, userId } })} /></FieldGroup></SettingsCard>
  </div>
}

function ProxySettingsPanel() {
  const query = useQuery({ queryKey: ['system-proxy'], queryFn: async () => (await apiGet<DataResponse<ProxySettings>>('/api/web/v1/system/proxy')).data })
  const [values, setValues] = useState<ProxySettings | null>(null)
  useEffect(() => { if (query.data) setValues(query.data) }, [query.data])
  const save = useApiMutation<ProxySettings, DataResponse<OperationResult>>({ mutationFn: (body) => apiPut('/api/web/v1/system/proxy', body), successMessage: '代理设置已保存', invalidate: [['system-proxy']] })
  const test = useApiMutation<ProxySettings, DataResponse<OperationResult>>({ mutationFn: (body) => apiPost('/api/web/v1/system/proxy/test', body), successMessage: '代理连接测试成功' })
  if (query.isError) return <QueryError error={query.error} retry={() => void query.refetch()} />
  if (!values) return <LoadingTable />
  return <Card><CardHeader><CardTitle>系统网络代理</CardTitle><CardDescription>供需要外部网络访问的功能统一使用。</CardDescription></CardHeader><CardContent><form className="flex max-w-2xl flex-col gap-5" onSubmit={(event) => { event.preventDefault(); save.mutate(values) }}><FieldGroup><Field><FieldLabel>代理类型</FieldLabel><Select items={['http', 'https', 'sock4', 'sock5', 'sock5h'].map((value) => ({ value, label: value.toUpperCase() }))} value={values.type} onValueChange={(type) => setValues({ ...values, type: type as ProxySettings['type'] })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{['http', 'https', 'sock4', 'sock5', 'sock5h'].map((value) => <SelectItem key={value} value={value}>{value.toUpperCase()}</SelectItem>)}</SelectGroup></SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><TextField label="代理服务器" value={values.server} onChange={(server) => setValues({ ...values, server })} /><NumberField label="端口" value={values.port} onChange={(port) => setValues({ ...values, port })} /></div><div className="grid gap-4 sm:grid-cols-2"><TextField label="用户名" value={values.username} onChange={(username) => setValues({ ...values, username })} /><TextField label="密码" type="password" value={values.password} onChange={(password) => setValues({ ...values, password })} /></div></FieldGroup><div className="flex gap-2"><Button type="submit" disabled={save.isPending}>{save.isPending ? <Spinner data-icon="inline-start" /> : <SaveIcon data-icon="inline-start" />}保存</Button><Button type="button" variant="outline" disabled={test.isPending} onClick={() => test.mutate(values)}>{test.isPending ? <Spinner data-icon="inline-start" /> : <FlaskConicalIcon data-icon="inline-start" />}测试连接</Button></div></form></CardContent></Card>
}

function CronSettingsPanel() {
  const query = useQuery({ queryKey: ['system-cron'], queryFn: async () => (await apiGet<DataResponse<CronSettings>>('/api/web/v1/system/cron')).data })
  const [mode, setMode] = useState<'shell' | 'http'>('shell')
  const [accessKey, setAccessKey] = useState('')
  useEffect(() => { if (query.data) { setMode(query.data.executionMode); setAccessKey(query.data.accessKey) } }, [query.data])
  const save = useApiMutation<void, DataResponse<OperationResult>>({ mutationFn: () => apiPut('/api/web/v1/system/cron', { executionMode: mode, accessKey }), successMessage: '后台任务设置已保存', invalidate: [['system-cron']] })
  if (query.isError) return <QueryError error={query.error} retry={() => void query.refetch()} />
  if (query.isPending) return <LoadingTable />
  return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>执行方式</CardTitle><CardDescription>选择服务器计划任务或受密钥保护的 HTTP 调用。</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-5" onSubmit={(event) => { event.preventDefault(); save.mutate() }}><FieldGroup><SelectField label="执行方式" value={mode} options={['shell', 'http']} onChange={(value) => setMode(value as 'shell' | 'http')} />{mode === 'http' ? <TextField label="访问密钥" type="password" value={accessKey} onChange={setAccessKey} /> : null}</FieldGroup><Button type="submit" disabled={save.isPending}>{save.isPending ? <Spinner data-icon="inline-start" /> : <SaveIcon data-icon="inline-start" />}保存</Button></form>{mode === 'shell' && query.data.shellCommand ? <CopyValue label="Shell 命令" value={query.data.shellCommand} /> : null}{mode === 'http' && query.data.publicUrl ? <CopyValue label="公开 URL" value={query.data.publicUrl} /> : null}</CardContent></Card><Card><CardHeader><CardTitle>最近运行</CardTitle><CardDescription>各类后台任务最后一次执行时间。</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{Object.entries({ certificateRenewal: '证书续签', certificateDeployment: '证书部署', domainExpiryNotice: '域名到期提醒', optimizeIp: '优选 IP', scheduledDns: '定时解析' }).map(([key, label]) => <div key={key}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{displayValue(query.data.lastRuns[key as keyof CronSettings['lastRuns']])}</p></div>)}</CardContent></Card></div>
}

function SettingsCard({ title, description, onSave, onTest, pending, children }: { title: string; description: string; onSave: () => void; onTest?: () => void; pending: boolean; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="flex flex-col gap-5">{children}<div className="flex gap-2"><Button disabled={pending} onClick={onSave}>{pending ? <Spinner data-icon="inline-start" /> : <SaveIcon data-icon="inline-start" />}保存</Button>{onTest ? <Button variant="outline" disabled={pending} onClick={onTest}><SendIcon data-icon="inline-start" />发送测试</Button> : null}</div></CardContent></Card> }
function TextField({ label, value, type = 'text', onChange }: { label: string; value: string; type?: string; onChange: (value: string) => void }) { return <Field><FieldLabel>{label}</FieldLabel><Input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></Field> }
function NumberField({ label, value, onChange }: { label: string; value: number | null; onChange: (value: number | null) => void }) { return <Field><FieldLabel>{label}</FieldLabel><Input type="number" min={1} max={65535} value={value ?? ''} onChange={(event) => onChange(event.target.value ? Number(event.target.value) : null)} /></Field> }
function AreaField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Field><FieldLabel>{label}</FieldLabel><Textarea rows={5} value={value} onChange={(event) => onChange(event.target.value)} /></Field> }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <Field><FieldLabel>{label}</FieldLabel><Select items={options.map((item) => ({ value: item, label: item }))} value={value} onValueChange={(next) => onChange(next ?? '')}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{options.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectGroup></SelectContent></Select></Field> }
function CopyValue({ label, value }: { label: string; value: string }) { return <div className="mt-5"><p className="mb-2 text-xs text-muted-foreground">{label}</p><div className="flex gap-2"><code className="min-w-0 flex-1 break-all rounded-lg bg-muted p-3 text-xs">{value}</code><Button size="icon" variant="outline" aria-label={`复制${label}`} onClick={() => { void navigator.clipboard.writeText(value); toast.add({ title: '已复制', type: 'success' }) }}><CopyIcon /></Button></div></div> }
